### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tschinz** [gornostal/Chrome-Bookmarks-Online#3]
Hello gornostal,
love your Chrome-Bookmakrs-Online project. I use it a lot. Just wanted to know if it's possible to make a feature request.
1. It would be great if the focus would be on load already on the search field.
2. Choice of open a link in a new tab or in the same window would be great too. For myself I modified the code to open a link always in a new tab.

keep up the good work

**Comment by gornostal** [comment]
@tschinz I added autofocus on the search input - it was easy.
But I don't want to add anything new to the interface. So if you want to open links in a new tab, please make changes to the code in your fork, as you did before.
